opt_type: "scmvae_sd21"

opt:
  dataset_names: ["spatialgen"]
  spatialgen_data_dir: "/data-nas/data/dataset/qunhe/PanoRoom/roomverse_data/processed_data_8k"
  train_split_file: "/data-nas/data/dataset/qunhe/PanoRoom/roomverse_data/processed_data_8k/8k_perspective_trains.txt"

optimizer:
  name: "adamw"
  lr: 0.0001
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.01
  eps: 1.e-8

lr_scheduler:
  name: "constant_warmup"
  num_warmup_steps: 1000

train:
  batch_size_per_gpu: 8
  epochs: 10000
  log_freq: 50
  early_eval_freq: 100
  eval_freq: 1000
  save_freq: 1000
  eval_freq_epoch: 10
  save_freq_epoch: 10
  ckpts_total_limit: 10
  ema_kwargs:
    decay: 0.9999
    use_ema_warmup: true
    inv_gamma: 1.
    power: 0.75

val:
  batch_size_per_gpu: 1